### ISSUE TITLE
Running issues

### ISSUE THREAD

**Issue by nikolaygit** [pollen8/plume#1]
Hi @pollen8 ,
thank you for the demo app! I tried to run it, but run into an issue. Any suggestions how to fix it?
- Added [missing package.json dependencies](https://github.com/nikolayhg/plume/commit/bcc21c7cbc2df8019305be2195fb2dbc56e44fcd)
- Run `node app.js`
- Opened `http://0.0.0.0:9999/` and saw in the browser:

![Screenshot](http://i.imgur.com/wS6mFs8.png)

I could not click in the editor and edit the contents.
- After about 1 minute the browser console showed:

```
Could not subscribe: Object {err: "connection to [192.168.33.101:27017] timed out"} docs hello2 share.uncompressed.js:991

Object {err: "connection to [192.168.33.101:27017] timed out"} 
```

**Comment by pollen8** [comment]
Hi
do you have mongo db installed?
It might be running on a different port /host if so you can edit that in the server/config.js file.

It also looks like something else isn't loading as normally the quill.js editor should load its template css.

If you make a PR for the missing dependencies, I'll add those in.

**Comment by hatpick** [comment]
I tried it, looks good. Cursors are a little bit "eeh", specially when user selects a portion of content. there are some missing packages.

@nikolayhg `mongod --dbpath=data/`, obviously you need to have a folder in the current directory called data. Then edit `server/config.js` to have `127.0.0.1` instead of `192.168.33.101`

**Comment by pollen8** [comment]
Cool, glad to hear you got it running.
I agree with the cursors - its just using quill's default ones, and it would need some logic adding to not show your own cursor
